
apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
type: Opaque
data:
  google_client_id: <base64-encoded-client-id>
  google_client_secret: <base64-encoded-client-secret>
  session_secret: <base64-encoded-session-secret>