version: '3.7'
services:
  backend:
    image: backend:latest
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    secrets:
      - google_client_id
      - google_client_secret
      - session_secret
    volumes:
      - ./backend:/app
    networks:
      - app-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  frontend:
    image: frontend:latest
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

secrets:
  google_client_id:
    external: true
  google_client_secret:
    external: true
  session_secret:
    external: true

networks:
  app-network:
    driver: overlay